  output: 'generated_bindings.dart'
  name: 'RtkLib'
  description: 'Bindings to SQLite'
  headers:
    entry-points:
      - 'folder/**.h'
      - 'folder/specific_header.h'
    include-directives:
      - '**index.h'
      - '**/clang-c/**'
      - '/full/path/to/a/header.h'